sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t harms2a/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true harms2a/react-test npm test

after_success:
  - docker build -t harms2a/multi-client ./client
  - docker build -t harms2a/multi-nginx ./nginx
  - docker build -t harms2a/multi-server ./server
  - docker build -t harms2a/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push harms2a/multi-client
  - docker push harms2a/multi-nginx
  - docker push harms2a/multi-server
  - docker push harms2a/multi-worker

deploy:
  provider: 'elasticbeanstalk'
  region: 'us-east-2'
  app: 'Docker-multi'
  env: 'Docker-multi-env'
  bucket_name: 'elasticbeanstalk-us-east-2-300276692915'
  bucket_path: 'docker-multi'
  on:
    branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY